diff --git a/Makefile b/Makefile
index f9dd25361..abd9e1eb7 100644
--- a/Makefile
+++ b/Makefile
@@ -13,8 +13,8 @@ ENABLE_TCL := 1
 ENABLE_ABC := 1
 ENABLE_GLOB := 1
 ENABLE_PLUGINS := 1
-ENABLE_READLINE := 1
-ENABLE_EDITLINE := 0
+ENABLE_READLINE := 0
+ENABLE_EDITLINE := 1
 ENABLE_GHDL := 0
 ENABLE_VERIFIC := 0
 ENABLE_VERIFIC_EDIF := 0
@@ -26,7 +26,7 @@ ENABLE_LIBYOSYS := 0
 ENABLE_ZLIB := 1
 
 # python wrappers
-ENABLE_PYOSYS := 0
+ENABLE_PYOSYS := 1
 
 # other configuration flags
 ENABLE_GCOV := 0
@@ -79,7 +79,7 @@ EXTRA_OBJS =
 EXTRA_TARGETS =
 TARGETS = $(PROGRAM_PREFIX)yosys$(EXE) $(PROGRAM_PREFIX)yosys-config
 
-PRETTY = 1
+PRETTY = 0
 SMALL = 0
 
 # Unit test
@@ -382,12 +382,7 @@ endif
 ifeq ($(ENABLE_PYOSYS),1)
 # Detect name of boost_python library. Some distros use boost_python-py<version>, other boost_python<version>, some only use the major version number, some a concatenation of major and minor version numbers
 CHECK_BOOST_PYTHON = (echo "int main(int argc, char ** argv) {return 0;}" | $(CXX) -xc -o /dev/null $(shell $(PYTHON_CONFIG) --ldflags) -l$(1) - > /dev/null 2>&1 && echo "-l$(1)")
-BOOST_PYTHON_LIB ?= $(shell \
-	$(call CHECK_BOOST_PYTHON,boost_python-py$(subst .,,$(PYTHON_VERSION))) || \
-	$(call CHECK_BOOST_PYTHON,boost_python-py$(PYTHON_MAJOR_VERSION)) || \
-	$(call CHECK_BOOST_PYTHON,boost_python$(subst .,,$(PYTHON_VERSION))) || \
-	$(call CHECK_BOOST_PYTHON,boost_python$(PYTHON_MAJOR_VERSION)) \
-)
+BOOST_PYTHON_LIB ?= 
 
 ifeq ($(BOOST_PYTHON_LIB),)
 $(error BOOST_PYTHON_LIB could not be detected. Please define manually)
