name: Build with Nix

on:
  push:

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [
            {
              name: "Ubuntu 22.04",
              family: "linux",
              runner: "ubuntu-22.04",
              archs: "x86_64",
            },
            ## Aarch64 is disabled for now: GitHub is committing to EOY
            ## for free aarch64 runners for open-source projects and
            ## emulation times out:
            ## https://github.com/orgs/community/discussions/19197#discussioncomment-10550689
            # {
            #   name: "Ubuntu 22.04",
            #   family: "linux",
            #   runner: "ubuntu-22.04",
            #   archs: "aarch64",
            # },
            {
              name: "macOS 13",
              family: "macos",
              runner: "macos-13",
              archs: "x86_64",
            },
            {
              name: "macOS 14",
              family: "macos",
              runner: "macos-14",
              archs: "arm64",
            },
            ## Windows is disabled because of an issue with compiling FFI as
            ## under MinGW in the GitHub Actions environment (SHELL variable has
            ## whitespace.)
            # {
            #   name: "Windows Server 2019",
            #   family: "windows",
            #   runner: "windows-2019",
            #   archs: "AMD64",
            # },
          ]
    name: Nix Builds | ${{ matrix.os.name }} | ${{ matrix.os.archs }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: openlane
          authToken: ${{ env.CACHIX_TOKEN }}
      - run: nix build .#ngspice

      # Add steps for your workflow here, such as building and testing your code
